version: 2

python:
  install:
    - path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  apt_packages:
    - doxygen
  tools:
    python: "3.11"
sphinx:
  configuration: doc/conf.py
